apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-app
  labels:
    app: employee-management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-management-app
  template:
    metadata:
      labels:
        app: employee-management-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "employee-management-app"
        dapr.io/app-port: "8000"
        dapr.io/config: "daprconfig"
    spec:
      containers:
      - name: employee-management-app
      #  image: clootrackneo.azurecr.io/neo/employee_management:latest
        image: demoregistry6789.azurecr.io/k8sdemo:ddea09ba6833b148ad7af0ebbd7a2b0b387a2b79
        envFrom:
        - configMapRef:
            name: employee-management-config
        ports:
        - containerPort: 8000
        imagePullPolicy: Always

