name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build -t your-docker-image:latest .
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: clootrackdevciacr01.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker Image to ACR
        run: |
         # docker tag employeev2:latest clootrackdevciacr01.azurecr.io/employeev2:latest
         # docker push demoregistry6789.azurecr.io/employeev2:latest
         docker build . -t ${{ secrets.ACR_USERNAME }}.azurecr.io/k8sdemo:${{ github.sha }}
         docker push ${{ secrets.ACR_USERNAME }}.azurecr.io/k8sdemo:${{ github.sha }}
         
      - name: Azure AKS Set Context
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: clootrack-dev-ci-aks-01
          resource-group: clootrack-dev-ci-data-rg

      - name: Print Original Content
        run: |
          echo "Original Content:"
          cat deployment/employee_managment.yaml

      - name: Replace Image Reference in Deployment YAML
        run: |
          $oldRef = "clootrackdevciacr01.azurecr.io/k8sdemo:latest"
          $newRef = "${{ secrets.ACR_USERNAME }}.azurecr.io/k8sdemo:${{ github.sha }}"
          $filePath = "deployment/employee_managment.yaml"

          $content = Get-Content -Path $filePath
          $updatedContent = $content -replace [regex]::Escape($oldRef), $newRef
          $updatedContent | Set-Content -Path $filePath

      - name: Print Updated Content
        run: |
         echo "Updated Content:"
         cat deployment/employee_managment.yaml


      - name: Kubectl Apply
        run: |
          kubectl apply -f deployment/employee_managment.yaml
          kubectl apply -f deployment/employee_managment_configmap.yaml
    
          
